name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fixed Step
        run: echo "working"
      - name: Print Message
        run: echo "Hello Devops"
      - name: List Files
        run: ls
